/**
 * Created by Administrator on 2018/6/11 0011.
 */
$(function () {
    var Menu=new Vue({
        el:"#menuContainer",
        data:{
            OneList:[
                {
                    "id":"1",
                    "name":"一级菜单一号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },{
                            "id":"11",
                            "name":"二级菜单三号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        },
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                },
                {
                    "id":"2",
                    "name":"一级菜单二号",
                    "TwoList":[
                        {
                            "id":"11",
                            "name":"二级菜单二号",
                            "threeList":[
                                {
                                    "id":"111",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"112",
                                    "name":"三级菜单三号"
                                },
                                {
                                    "id":"113",
                                    "name":"三级菜单三号"
                                }
                            ]
                        }
                    ]
                }
            ],
            menuOne:'',
            menuTwo:'',
            menuShow:false,
            menuTwoPath:0,
            menuThreePath:0,
            arrowsPath:1
        },
        methods:{
            /*显示隐藏菜单*/
            switchMenu:function () {
                this.menuShow=!this.menuShow;
                if(this.menuShow){
                    this.arrowsPath=2;
                    this.menuTwoPath=1;
                }else{
                    this.arrowsPath=1;
                    this.menuTwoPath=0;
                    this.menuThreePath=0;
                    setTimeout(function () {
                        this.menuTwo='';
                        this.menuOne='';
                    },300)
                }
            },
            /*二级菜单显示切换*/
            menuOneClick:function (item,index) {
                if(index!==this.menuOne){
                    if(this.menuTwoPath==2){
                        this.menuThreePath=0;
                        this.arrowsPath=2;
                        this.menuTwoPath=1;
                        var _this=this;
                        setTimeout(function () {
                            _this.menuTwo='';
                            _this.menuThreePath=1;
                            _this.menuOne=index;
                            _this.menuTwoPath=2;
                            _this.arrowsPath=3;
                        },300)
                    }else{
                        this.menuTwo='';
                        this.menuOne=index;
                        this.menuThreePath=1;
                        this.menuTwoPath=2;
                        this.arrowsPath=3;
                    }
                }
            },
            /*三级菜单显示*/
            menuTwoClick:function (item,index) {
                if(index!==this.menuTwo){
                    if(this.menuThreePath==2){
                        this.menuThreePath=1;
                        this.arrowsPath=3;
                        var _this=this;
                        setTimeout(function () {
                            _this.menuTwo=index;
                            _this.menuThreePath=2;
                            _this.arrowsPath=4;
                        },300)
                    }else{
                        this.menuTwo=index;
                        this.menuThreePath=2;
                        this.arrowsPath=4;
                    }
                }
            },
            lowAction:function (arr) {

            }
        },
        created:function () {
            /*$.ajax({
                url:"./data/api.php",
                type:"post",
                dataType:"json",
                data:{
                    function_name:'uf_show_goods_list',
                    as_type:001,
                    as_id:1,
                    as_page_qty:1 ,
                    as_json_goods_data:'',
                    as_json_banner:'',
                    as_json_filter:'',
                    as_goods_id:'',
                    as_goods_total:'',
                    as_error:''
                },
                success:function (res) {

                    /!*接收banner图片*!/
                    if(res.as_json_banner){
                        _this.bannerImg=JSON.parse('['+res.as_json_banner+']');
                        if(_this.bannerImg.length>1){
                            setInterval(function () {
                                if(_this.bannerIn){
                                    _this.nowImg+=1;
                                    if(_this.nowImg>_this.bannerImg.length-1){
                                        _this.nowImg=0;
                                    }
                                }
                            },5000);
                        }

                    }
                    console.log(res.as_goods_id.split(','));

                    /!*接收筛选数据后显示前两条筛选*!/
                    if(res.as_json_filter) {
                        _this.filterData = JSON.parse('[' + res.as_json_filter + ']');
                        if (_this.filterData.length > 2) {
                            _this.showFilter.push(_this.filterData[0]);
                            _this.showFilter.push(_this.filterData[1]);
                        } else {
                            _this.showFilter = _this.filterData;
                        }
                    }

                    /!*接收商品数据*!/
                    if(res.as_json_goods_data){
                        _this.goodsData.goodsList = JSON.parse('[' + res.as_json_goods_data + ']');
                        _this.goodsIdStr=res.as_goods_id;

                        _this.getArrId(res.as_goods_id);

                    }else{
                        _this.showAll=false;
                    }



                }
            });*/
        }
    })
});